# Generated by Django 6.1.1 on 2026-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('new_users_count', models.PositiveIntegerField(default=0, verbose_name='Новых пользователей')),
                ('calendar_clicks', models.PositiveIntegerField(default=0, verbose_name='Кликов по календарю')),
                ('events_created_all_day', models.PositiveIntegerField(default=0, verbose_name="Событий 'Весь день'")),
                ('events_created_exact', models.PositiveIntegerField(default=0, verbose_name="Событий 'Точное время'")),
                ('events_created_interval', models.PositiveIntegerField(default=0, verbose_name="Событий 'Интервал'")),
                ('events_edited', models.PositiveIntegerField(default=0, verbose_name='Изменено событий')),
                ('events_deleted', models.PositiveIntegerField(default=0, verbose_name='Удалено событий')),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
                'ordering': ['-date'],
            },
        ),
    ]
