# Generated by Django 6.1.1 on 2026-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_create_model_Appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_cancelled',
            field=models.PositiveIntegerField(default=0, verbose_name='Отменено/удалено событий'),
        ),
        migrations.AddField(
            model_name='user',
            name='events_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Создано событий'),
        ),
        migrations.AddField(
            model_name='user',
            name='events_edited',
            field=models.PositiveIntegerField(default=0, verbose_name='Отредактировано событий'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Ожидание'), ('confirmed', '✅ Подтверждено'), ('cancelled', '❌ Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
