# Generated by Django 6.1.1 on 2026-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_user_activity_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Доступно ли событие для просмотра другим пользователям', verbose_name='Публичное'),
        ),
    ]
