# Generated by Django 6.1.1 on 2026-09-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_flag_is_public_in_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Токен'),
        ),
    ]
