# Generated by Django 6.1.1 on 2026-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_api_token_in_User'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания токена'),
        ),
    ]
