services:
  db:
    image: postgres:16-alpine
    container_name: calendar_bot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-calendar_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5444}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: