[project]
name = "telegram-bot-calendar-notes"
version = "0.1.0"
description = "Async Telegram bot with calendar and notes functionality"
authors = [
    {name = "Evgeniy",email = "evgeniy.migun@mail.ru"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "python-telegram-bot>=21.0,<22.0",
    "pydantic-settings>=2.0.0,<3.0.0",
    "psycopg2-binary>=2.9.0,<3.0.0",
    "asyncpg>=0.29.0,<0.32.0"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
[dependency-groups]
dev = [
    "mypy (>=2.1.0,<3.0.0)",
    "asyncpg-stubs (>=0.31.2,<0.32.0)"
]

[tool.mypy]
explicit_package_bases = true
plugins = [
    "pydantic.mypy"
]