import itertools

# Создаем генератор, который начинает с 0 и при каждом вызове next() увеличивает значение на 1
_state = itertools.count()

CHOOSING_ACTION = next(_state)
CHOOSING_TIME = next(_state)
WAITING_FOR_TITLE = next(_state)
WAITING_FOR_DESC_CHOICE = next(_state)
WAITING_FOR_DESCRIPTION = next(_state)
WAITING_FOR_TIME_INPUT_EXACT = next(_state)
WAITING_FOR_TIME_INPUT_INTERVAL = next(_state)
CONFIRMING_DELETE = next(_state)
CHOOSING_EVENT_TO_DELETE = next(_state)
TYPING_EVENT_NUMBER_TO_DELETE = next(_state)
CHOOSING_EDIT_FIELD = next(_state)
SELECTING_EDIT_EVENT = next(_state)
TYPING_EDIT_NUM = next(_state)
TYPING_EDIT_TITLE = next(_state)
TYPING_EDIT_DESC = next(_state)
TYPING_EDIT_TIME = next(_state)
TYPING_EDIT_DATE = next(_state)
SELECTING_INVITE_EVENT = next(_state) # Выбор инлайн-кнопкой (2-10 событий)
TYPING_INVITE_NUM = next(_state)      # Ввод номера текстом (>10 событий)
TYPING_INVITEE_ID = next(_state)
TYPING_PUBLIC_EVENTS_USER_ID = next(_state)